export default {
    pageId: null,
    selectedId: null,
    multiSelected: null,
    activeTab: 'content',
    cachedControls: null,
    cachedSettings: null,
    cachedStyles: null,
    cachedElementId: null,
    history: [],
    historyIndex: -1,
    responsiveMode: 'desktop',
    responsiveTab: 'desktop',
    csrf: '',
    saving: false,
    dirty: false,
    zoomLevel: 100,
    isFullscreen: false,
    _timers: {},
    _lastElements: [],
    _clipboard: null,
    _styleClipboard: null,
    _imagePasteHandler: null,
};
